=== nathanmathewv/InformationConvergencePlatform/Schemas/univ_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://iiitb.ac.in/team_5"
    xmlns="http://iiitb.ac.in/team_5"
    elementFormDefault="qualified">
    <xs:element name="unified_schema">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="entity_type" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:int"/>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="ds">
                                <xs:complexType>
                                    <xs:choice maxOccurs="unbounded">
                                        <xs:element name="dbconfig"></xs:element>
                                        <xs:element name="db">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="dbname" type="xs:string"/>
                                                    <xs:element name="host" type="xs:string"/>
                                                    <xs:element name="port" type="xs:int"/>
                                                    <xs:element name="user" type="xs:string"/>
                                                    <xs:element name="password" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="root" type="xs:string"/>
                                        <xs:element name="table" type="xs:string"/>
                                        <xs:element name="file" type="xs:string"/>
                                        <xs:element name="sheet" type="xs:string"/>
                                        <xs:element name="FolderName" type="xs:string"/>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="type" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Table"/>
                                    <xs:enumeration value="XML"/>
                                    <xs:enumeration value="PDF"/>
                                    <xs:enumeration value="SQL"/>
                                    <xs:enumeration value="Spreadsheet"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="link" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="source">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="id" type="xs:int"/>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="p_key" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="target">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="id" type="xs:int"/>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="f_key" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nathanmathewv/InformationConvergencePlatform/sample_schema2.xml
<?xml version="1.0" encoding="UTF-8"?>
<unified_schema xmlns="http://iiitb.ac.in/team_5"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://iiitb.ac.in/team_5 univ_schema.xsd">
    
    <entity_type type = "SQL">
        <id>1</id>
        <name>employee</name>
        <ds>
            <dbconfig>
                <database>company</database>
                <host>localhost</host>
                <port>3306</port>
                <user>root</user>
                <password>4902617</password>
            </dbconfig>
            <table>employee</table>
        </ds>
    </entity_type>

    <entity_type type = "SQL">
        <id>5</id>
        <name>department</name>
        <ds>
            <dbconfig>
                <database>company</database>
                <host>localhost</host>
                <port>3306</port>
                <user>root</user>
                <password>4902617</password>
            </dbconfig>
            <table>department</table>
        </ds>
    </entity_type>

    <entity_type type = "Spreadsheet">
        <id>2</id>
        <name>Sellers</name>
        <ds>
            <file>Sellers.xlsx</file>
            <sheet>Sellers</sheet>
        </ds>
    </entity_type>

    <entity_type type = "XML">
        <id>3</id>
        <name>PurchaseOrders</name>
        <ds>
            <FolderName>PurchaseOrders</FolderName>
        </ds> 
    </entity_type>

    <entity_type type = "PDF">
        <id>4</id>
        <name>Invoice</name>
        <ds>
            <FolderName>Invoices</FolderName>
        </ds>
    </entity_type>

    <link>
        <source>
                <id>1</id>
                <name>Customer</name>
                <p_key>CustID</p_key>
        </source>
        <target>
                <id>3</id>
                <name>Purchase_Orders</name>
                <f_key>CustID</f_key>
        </target>
        
    </link>
</unified_schema>

=== nathanmathewv/InformationConvergencePlatform/Schemas/sample_schema_ayush.xml
<?xml version='1.0' encoding='UTF-8'?>
<unified_schema xmlns='http://iiitb.ac.in/team_5'
      xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
      xsi:schemaLocation='http://iiitb.ac.in/team_5 univ_schema.xsd'>
    
    <entity_type type = 'SQL'>
        <id>1</id>
        <name>customer</name>
        <ds>
            <dbconfig>
                <database>DmProject</database>
                <host>localhost</host>
                <port>3306</port>
                <user>testuser</user>
                <password>newpassword</password>
            </dbconfig>
            <table>customer</table>
        </ds>
    </entity_type>

    <entity_type type = 'SQL'>
        <id>5</id>
        <name>region</name>
        <ds>
            <dbconfig>
                <database>DmProject</database>
                <host>localhost</host>
                <port>3306</port>
                <user>testuser</user>
                <password>newpassword</password>
            </dbconfig>
            <table>region</table>
        </ds>
    </entity_type>

    <entity_type type = 'Spreadsheet'>
        <id>2</id>
        <name>Sellers</name>
        <ds>
            <file>Datasources/Sellers.xlsx</file>
            <sheet>Sellers</sheet>
        </ds>
    </entity_type>

    <entity_type type = 'XML'>
        <id>3</id>
        <name>PurchaseOrders</name>
        <ds>
            <FolderName>Datasources/PurchaseOrders</FolderName>
            <root>PurchaseOrder</root>
        </ds> 
    </entity_type>

    <entity_type type = 'XML'>
        <id>7</id>
        <name>Products</name>
        <ds>
            <FolderName>Datasources/Products</FolderName>
            <root>Product</root>
        </ds> 
    </entity_type>
</unified_schema>
